#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "datacalc-controller-poc.fullname" . }}
  labels:
{{ include "datacalc-controller-poc.labels" . | indent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.prometheus.path | quote }}
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
{{ include "datacalc-controller-poc.product-info" . | indent 4 }}
{{- include "datacalc-controller-poc.config-annotations" . | indent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily -}}
  ipFamily: {{ .Values.global.internalIPFamily | quote }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "datacalc-controller-poc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
